### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by agrgn42** [DanielJDufour/location-extractor#2]
In attempting to run the following test code in python3:

from location_extractor import extract_locations
text = "I arrived in New York on January 4, 1937"
locations = extract_locations(text)

I received the following error:

Traceback (most recent call last):
  File "test_geo_code.py", line 1, in <module>
    from location_extractor import extract_locations
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/location_extractor/__init__.py", line 112
    if debug: print "starting extract_locations_from_text"
                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(debug: print "starting extract_locations_from_text")?

Does location_extractor support python3?

**Comment by DanielJDufour** [comment]
@agrgn42 , thanks for catching this!  I just made an update to the GitHub repo and PyPI, so just do `pip install --upgrade location-extractor` and it should work.

Please let me know if you catch any other errors.  I'm happy to help!

**Comment by agrgn42** [comment]
@DanielJDufour Thanks so much for the quick reply and update! The test ran perfectly after the update. I'll be sure to make a note if any other issues come up. Very helpful package, thanks for writing and sharing!

**Comment by DanielJDufour** [comment]
@agrgn42 , great. I'll close this issue for now.  Feel free to create new issues in the future if you come across them.  Have a good week.
